### ISSUE TITLE
Cyrillic is replaced

### ISSUE THREAD

**Issue by axperien** [haensl/gulp-embed-svg#2] opened 2018-08-08 14:30 UTC
Hi!  
Thanks for the plugin!  
There is a small problem. Cyrillic in the file is replaced with unicode.  

`<span>Узнай о нас больше</span>`  

`<span>&#x423;&#x437;&#x43D;&#x430;&#x439; &#x43E; &#x43D;&#x430;&#x441; &#x431;&#x43E;&#x43B;&#x44C;&#x448;&#x435;</span>`  

How can this be avoided?

**Comment by haensl** [comment] 2018-08-08 14:36
Hi axperien,

first of all: thanks for reporting this issue!

Can you maybe provide me with a sample setup? E.g. some HTML and gulp task you used?
That would make it easier for me to reproduce the issue.

**Comment by haensl** [comment] 2018-08-12 16:34
I found out that this was caused by [htmlparser2's option `decodeEntities`](https://github.com/fb55/htmlparser2/wiki/Parser-options) via [cheerio's `$.html` which defaults this to `true`](https://github.com/cheeriojs/cheerio/issues/711).
I therefore [published a new version which adds the `decodeEntities` parameter](https://www.npmjs.com/package/gulp-embed-svg), which defaults to `false` and therefore fixes your problem. If you ever want to encode decoded html entities, set it to `true`.

Please use the latest version and let me know if you still have experience any problems.

**Comment by haensl** [comment] 2018-08-12 16:35
Fixed in v1.0.1

**Closed by haensl** 2018-08-12 16:35 UTC
Labels: bug
