### ISSUE TITLE
Error: Callback called multiple times

### ISSUE THREAD

**Issue by budfy** [haensl/gulp-embed-svg#27] opened 2021-01-16 12:41 UTC
Hello!
I am getting a bug with this plugin when I compile an html file and I don’t know how to fix this error.
I collect html from components using the Gulp-File-Include plugin, and then I want to run it through the pipe of your plugin. Locally, everything works well, but if I remove the node modules and install them again (for example, I clone a remote repository), and then run the plugin, then an error occurs with the following text:
`[14:31:41] Error: Callback called multiple times`
`at Transform.afterTransform (D:\OpenServer\domains\rolio\node_modules\gulp-file-include\node_modules\readable-stream\lib\_stream_transform.js:82:31)`
`at Transform.fileInclude [as _transform] (D:\OpenServer\domains\rolio\node_modules\gulp-file-include\lib\index.js:60:9)`
`at Transform._read (D:\OpenServer\domains\rolio\node_modules\gulp-file-include\node_modules\readable-stream\lib\_stream_transform.js:177:10)`
`at Transform._write (D:\OpenServer\domains\rolio\node_modules\gulp-file-include\node_modules\readable-stream\lib\_stream_transform.js:164:83)`
`at doWrite (D:\OpenServer\domains\rolio\node_modules\gulp-file-include\node_modules\readable-stream\lib\_stream_writable.js:409:139)`
`at writeOrBuffer (D:\OpenServer\domains\rolio\node_modules\gulp-file-include\node_modules\readable-stream\lib\_stream_writable.js:398:5)`
`at Transform.Writable.write (D:\OpenServer\domains\rolio\node_modules\gulp-file-include\node_modules\readable-stream\lib\_stream_writable.js:307:11)`
`at DestroyableTransform.ondata (D:\OpenServer\domains\rolio\node_modules\readable-stream\lib\_stream_readable.js:619:20)`
`at DestroyableTransform.emit (events.js:315:20)`
`at DestroyableTransform.EventEmitter.emit (domain.js:548:15)`
`[14:31:41] 'default' errored after 386 ms`
`npm ERR! code 1`
`npm ERR! path D:\OpenServer\domains\rolio`
`npm ERR! command failed`
`npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "gulp"`
`npm ERR! A complete log of this run can be found in:`
`npm ERR!     C:\Users\serdy\AppData\Local\npm-cache\_logs\2021-01-16T12_31_41_725Z-debug.log`

Please help me to solve this problem. An example of not working code in [this repository](https://github.com/budfy/Easy-webdev-startpack).

**Comment by budfy** [comment] 2021-01-16 12:55
I tried to run the plugin on a clean html file, without inclusions, and again got an error, only with a different content:
`[14:53:17] TypeError: Cannot read property 'lang' of undefined`
`at Object.exports.getAttrList (D:\OpenServer\domains\rolio\node_modules\parse5-htmlparser2-tree-adapter\lib\index.js:283:53)`
`at Serializer._serializeAttributes (D:\OpenServer\domains\rolio\node_modules\parse5\lib\serializer\index.js:99:40)`
`at Serializer._serializeElement (D:\OpenServer\domains\rolio\node_modules\parse5\lib\serializer\index.js:67:14)`
`at Serializer._serializeChildNodes (D:\OpenServer\domains\rolio\node_modules\parse5\lib\serializer\index.js:50:26)`
`at Serializer.serialize (D:\OpenServer\domains\rolio\node_modules\parse5\lib\serializer\index.js:36:14)`
`at Object.exports.serialize (D:\OpenServer\domains\rolio\node_modules\parse5\lib\index.js:28:23)`
`at render (D:\OpenServer\domains\rolio\node_modules\cheerio\lib\static.js:101:17)`
`at Function.exports.html (D:\OpenServer\domains\rolio\node_modules\cheerio\lib\static.js:137:10)`
`at DestroyableTransform._transform (D:\OpenServer\domains\rolio\node_modules\gulp-embed-svg\index.js:150:41)`
`at DestroyableTransform.Transform._read (D:\OpenServer\domains\rolio\node_modules\readable-stream\lib\_stream_transform.js:184:10)`

**Comment by haensl** [comment] 2021-01-20 12:49
Hi,

can you please provide the HTML you use as input?

**Comment by haensl** [comment] 2021-01-26 08:58
@budfy have you tried setting the `root` directory option to an absolute path?

https://github.com/budfy/Easy-webdev-startpack/blob/2c79b0012b2ef09692e55ac12094e7a119118736/gulpfile.js#L170

Also, I think a fully rendered HTML would be good for debugging, could you provide the plain HTML rendered your PHP application?

**Comment by haensl** [comment] 2021-02-16 15:39
Closing this since there is no reply and I cannot reproduce.

**Closed by haensl** 2021-02-16 15:39 UTC
